name: 2842 test
on:
  workflow_dispatch:
jobs:
  job1:
    environment: ${{ fromJSON('{"refs/heads/main":"Production"}')[github.event.ref] || 'PublicEnvironmentForPullRequests' }}
    steps:
      - run: sleep 20
      - run: echo ${{ SECRETS.SECRET_ONLY_AVAILABLE_IN_Production }} | wc --bytes
