name: Approve PRs
on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Don't think, just approve"
        run: |
          echo Approving PR ${{github.event.pull_request.number}}
          gh pr review ${{github.event.pull_request.number}} --approve --repo ${{github.event.pull_request.repository.full_name}}
