name: Call center

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - run: echo In da call center~~
  build:
    uses: "anywherepilot-playground/bbq-pilots/.github/workflows/called.yml@main"
