name: Install Go
on:
  workflow_dispatch:
jobs:
  gofmt:
    name: Go fmt
    runs-on: self-hosted macOS
    steps:
      - name: Install go 1.16.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.2
