name: Graphite
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo Hello, world!
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo Hello, world!
  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo Hello, world!
  job_4:
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo Hello, world!
  job_5:
    runs-on: ubuntu-latest
    needs: [job_1]
    steps:
      - name: Job 5
        run: echo Hello, world!
  job_6:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - name: Job 6
        run: echo Hello, world!
  job_7:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - name: Job 7
        run: echo Hello, world!
  job_8:
    runs-on: ubuntu-latest
    needs: [job_1, job_4]
    steps:
      - name: Job 8
        run: echo Hello, world!
