name: Call center

# Controls when the workflow will run
on:
  schedule:
    - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: "anywherepilot-playground/bbq-publica/.github/workflows/called.yml@main"
